############################################
#### Server
server.port: 8080
spring:
  profiles.active: local

  #### JPA
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

############################################
#### Logging
logging.level:
  org.hibernate.orm.jdbc.bind: trace

############################################
#### swagger-ui
springdoc:
  swagger-ui:
    display-request-duration: true